# Generated by Django 5.2.4 on 2025-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', 'add_houses_and_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
