# Generated by Django 5.2.4 on 2025-07-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ARAVALI', 'ARAVALI'), ('NILGIRI', 'NILGIRI'), ('SHIVALIKSHIVALIK', 'Shivalik'), ('UDAIGIRIUDAIGIRI', 'Udaigiri')], max_length=100)),
            ],
        ),
    ]
