# Generated by Django 5.2.4 on 2025-07-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_houses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='evening_class_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='games_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='morning_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='morning_pt_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='night_dorm_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.houses'),
        ),
    ]
