# Generated by Django 5.2.4 on 2025-07-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_branch_alter_user_options_alter_user_is_active_and_more'),
        ('attendance', '0005_remove_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
    ]
