# Generated by Django 5.2.4 on 2025-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='evening_class_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW'), ('NOT_MARKED', 'NOT_MARKED')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='games_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW'), ('NOT_MARKED', 'NOT_MARKED')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW'), ('NOT_MARKED', 'NOT_MARKED')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_pt_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW'), ('NOT_MARKED', 'NOT_MARKED')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='night_dorm_attendance',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('ON_DUTY', 'ON_DUTY'), ('LEAVE', 'LEAVE'), ('LEAVE_SW', 'LEAVE_SW'), ('NOT_MARKED', 'NOT_MARKED')], default='NOT_MARKED', max_length=100, null=True),
        ),
    ]
