# Generated by Django 5.2.4 on 2025-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_evening_class_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='evening_class_attendance',
            field=models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent'), ('ON_DUTY', 'on_duty'), ('LEAVE', 'leave'), ('LEAVE_SW', 'leave_sw'), ('NOT_MARKED', 'not_marked')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='games_attendance',
            field=models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent'), ('ON_DUTY', 'on_duty'), ('LEAVE', 'leave'), ('LEAVE_SW', 'leave_sw'), ('NOT_MARKED', 'not_marked')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_attendance',
            field=models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent'), ('ON_DUTY', 'on_duty'), ('LEAVE', 'leave'), ('LEAVE_SW', 'leave_sw'), ('NOT_MARKED', 'not_marked')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_pt_attendance',
            field=models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent'), ('ON_DUTY', 'on_duty'), ('LEAVE', 'leave'), ('LEAVE_SW', 'leave_sw'), ('NOT_MARKED', 'not_marked')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='night_dorm_attendance',
            field=models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent'), ('ON_DUTY', 'on_duty'), ('LEAVE', 'leave'), ('LEAVE_SW', 'leave_sw'), ('NOT_MARKED', 'not_marked')], default='NOT_MARKED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='name',
            field=models.CharField(choices=[('ARAVALI_SR', 'aravali_sr'), ('NILGIRI_SR', 'nilgiri_sr'), ('SHIVALIK_SR', 'shivalik_sr'), ('UDAIGIRI_SR', 'udaigiri_sr'), ('ARAVALI_JR', 'aravali_jr'), ('NILGIRI_JR', 'nilgiri_jr'), ('SHIVALIK_JR', 'shivalik_jr'), ('UDAIGIRI_JR', 'udaigiri_jr')], max_length=100),
        ),
    ]
