# Generated by Django 5.2.4 on 2025-08-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_branch_alter_user_options_alter_user_is_active_and_more'),
        ('attendance', '0009_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'classroom', 'branch')},
        ),
    ]
