# Generated by Django 5.2.4 on 2025-08-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_student_course'),
        ('attendance', '0013_pushsubscription_notificationlog'),
    ]

    operations = [
    ]
